server:
  port: 8761


spring:
  application:
    name: Eureka-Server



eureka:
  client:
    service-url:
      defaultZone: http://eureka.grkfcs.cn/:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: 139.196.101.246
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 1
    prefer-ip-address: true

