server:
  port: 8761



eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka/
    register-with-eureka: true
    registryFetchIntervalSeconds: 5

  instance:
    ip-address: eureka.grkfcs.cn #决定Eureka服务显示host
    hostname: ${eureka.instance.ip-address} #决定服务跳转host，必须指定
    prefer-ip-address: true
    non-secure-port: 80
    instance-id: ${eureka.instance.ip-address}:${server.port}
spring:
  application:
    name: Eureka-Server