# Spring配置
spring:
  profiles:
    active: druid




feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000
eureka:
  client:
    service-url:
      defaultZone: http://eureka.grkfcs.cn/eureka/