# Spring配置
spring:
  profiles:
    active: druid


server:
  servlet:
    session:
      timeout: 1800s

feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000
security:
  # 开启认证，Spring Cloud2.0后添加jar会自动集成并开启
  # basic.enabled: true
  # 用户名密码
  user:
    name: admin
    password: admin



eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka.grkfcs.cn/eureka/
    fetchRegistry: true