# Spring配置
spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 300
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
server:
  servlet:
    session:
      timeout: 18000s

feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000
