# 开发环境配置
server:
  # 应用的访问路径
  context-path: /
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  port: 8083
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  resources:
    # 静态资源路径
    static-locations: classpath:static/


app:
  wxPayUrl: http://127.0.0.1:8082/pay
  wxAuthUrl: http://yuluncc.top/wechat/auth
    # 验证码开关
  captchaEnabled: false
spring:
  application:
    name: reward-video-web
  jmx:
    enabled: false
  cache:
    type: simple
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

debug: true

endpoints:
  dubbo:
    enabled: true


management:
  server:
    port: 8083
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
dubbo:
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    timeout: 15000
  protocol:
    port: 22345
    name: dubbo
    lazy: true
  application:
    name: reward-video-web
    id: reward-video-web
    qos:
      enable: true
      port: 33334
      foreign:
        ip: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka.grkfcs.cn/eureka/
    fetchRegistry: true