# Spring配置
spring:
  profiles:
    active: druid




feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000



eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/